baseURL = "https://jabasco.dev/"
languageCode = "en-us"
title = "jabasco.dev"

[params]
    author = "Jacob Bas"
    linkedIn = "https://www.linkedin.com/in/jacob-bas-52019714b/"
    github = "https://github.com/JacobBas"
